### ISSUE TITLE
Spaces in path

### ISSUE THREAD

**Issue by buschtoens** [geo8bit/nodebob#5]
The typical cmd horror. As soon as there's a space in the cwd everything fails.

**Comment by rthery** [comment]
To prevent this problem, build.bat needs to be edited to add quotes when storing the current folder:

``` batch
set CUR_DIR="%CD%"
```

I was planning to make a pull request, but for just 2 quotes to add in a file, it didn't seem worthwhile ;)

**Comment by buschtoens** [comment]
No shit. I could _swer_  that did not work, when I tried it. Haha!
Thank you good sir! :)

Have a :cookie:.

**Comment by buschtoens** [comment]
Fixed by #6.
